version: 1

cvp_setting:
   cvphost: cvp201612-furtakcvp201612-bczsuyux.srv.ravcloud.com
   cvpuser: cvpadmin
   cvppasswd: arista
   settings_configlet: jj_config
   dhcpprefixlen: /24
   mgmt_gw: 10.0.0.1
